sudo: false
language: java
services:
  - docker
jdk:
  - openjdk8

script:
  - "mvn versions:set -DnewVersion=$TRAVIS_BRANCH"
  - "mvn versions:commit"
  - "mvn clean"
  - "mvn install -P prod"
after_success:
  - mkdir push
  - cp ./backend/target/*.jar ./push

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ./push/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
  overwrite: true