stages:
- build
- before_deploy
- deploy
jobs:
  include:
  - stage: build
    language: android
    dist: trusty
    jdk:
    - openjdk8
    android:
      components:
      - build-tools-29.0.2
      - platform-tools
      - android-29
    before_install:
    - nvm install 12
    install:
    - npm install -g @quasar/cli
    - npm install -g cordova
    script:
    - openssl aes-256-cbc -K $encrypted_f2123cf90a35_key -iv $encrypted_f2123cf90a35_iv -in ./.travis/googleplay.keystore.enc -out ./.travis/googleplay.keystore -d
    - mvn versions:set -DnewVersion=$TRAVIS_BRANCH
    - mvn versions:commit
    - mvn clean
    - mvn install -P prod
    - mkdir push
    - cp ./backend/target/*.jar ./push
    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ./.travis/googleplay-key.keystore
      -storepass $GOOGLEPLAY_KEYSTORE_PASSPHRASE ./frontend/src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      googleplay-key
    - "${ANDROID_HOME}/build-tools/29.0.2/zipalign -v 4 ./frontend/src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      ./push/android-app.apk"
    deploy:
    - provider: releases
      api_key: "$GITHUB_TOKEN"
      file:
      - "./push/*"
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
      overwrite: true
    workspaces:
      create:
        name: target
        paths:
        - "./backend/target/"
        - "./push/"
  - stage: before_deploy
    language: sh
    services:
      - docker
    before_deploy:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG -f ./docker/Dockerfile
      ./
    - docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG alex9849/pi-cocktailmaker:latest
    - docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG-pi -f ./docker/DockerfilePi
      ./
    - docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG-pi alex9849/pi-cocktailmaker:latest-pi
    workspaces:
      use: target
    deploy:
      provider: script
      script: bash ./.travis/docker_deploy.sh
      on:
        tags: true
        overwrite: true
