services:
  - docker
jdk:
  - openjdk8

stages:
  - build
  - before_deploy
  - deploy

jobs:
  include:
    - stage: build
      language: java
      script:
        - "mvn versions:set -DnewVersion=$TRAVIS_BRANCH"
        - "mvn versions:commit"
        - "mvn clean"
        - "mvn install -P prod"
        - "mkdir push"
        - "cp ./backend/target/*.jar ./push"
        - "cp ./frontend/dist/cordova/apk/app-release-unsigned.apk ./push/android-app.apk"
      workspaces:
        create:
          name: target
          paths:
            - ./backend/target/
            - ./push/
    - stage: before_deploy
      language: node_js
      node_js:
        - 14
      before_install:
        - npm install -g @quasar/cli
        - npm install -g cordova
        - npm install frontend
      install:
        - "cd frontend && quasar build -m android"
      before_deploy:
        - "cp ./dist/cordova/apk/app-release-unsigned.apk ./push/android-app.apk"
      workspaces:
        use: target
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file:
            - ./push/*
          file_glob: true
          skip_cleanup: true
          on:
            tags: true
          overwrite: true
        - provider: script
          script: bash ./.travis/docker_deploy.sh
          on:
            tags: true
          overwrite: true
    - stage: before_deploy
      language: sh
      before_deploy:
        - "docker run --rm --privileged multiarch/qemu-user-static:register --reset"
        - "docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG -f ./docker/Dockerfile ./"
        - "docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG alex9849/pi-cocktailmaker:latest"
        - "docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG-pi -f ./docker/DockerfilePi ./"
        - "docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG-pi alex9849/pi-cocktailmaker:latest-pi"
      workspaces:
        use: target
      deploy:
        provider: script
        script: bash ./.travis/docker_deploy.sh
        on:
          tags: true
          overwrite: true