sudo: false
language: java
arch:
  - amd64
services:
  - docker
jdk:
  - openjdk8

stages:
  - build
  - before_deploy
  - deploy

jobs:
  include:
    - stage: build
      script:
        - "mvn versions:set -DnewVersion=$TRAVIS_BRANCH"
        - "mvn versions:commit"
        - "mvn clean"
        - "mvn install -P prod"
        - "mkdir push"
        - "cp ./backend/target/*.jar ./push"
      workspaces:
        create:
          name: target
          paths:
            - ./backend/target/
    - stage: before_deploy
      arch: amd64
      before_deploy:
        - "docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG ./backend"
        - "docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG alex9849/pi-cocktailmaker:latest"
      workspaces:
        use: target
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file:
            - ./push/*
          file_glob: true
          skip_cleanup: true
          on:
            tags: true
          overwrite: true
        - provider: script
          script: bash ./.travis/docker_deploy.sh
          on:
            tags: true
          overwrite: true
    - stage: before_deploy
      arch: arm64
      before_deploy:
        - "docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG-arm64 -f ./backend/DockerfileARM64 ./backend"
        - "docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG-arm64 alex9849/pi-cocktailmaker:latest-arm64"
      workspaces:
        use: target
      deploy:
        provider: script
        script: bash ./.travis/docker_deploy.sh
        on:
          tags: true
          overwrite: true