env:
  global:
    secure: joiIZNdxbLNGa92mgz6pSHbXufFLlRaTGfZM1T+Nl45P5lxwjmNQUFuH8ENalvhmObyNRjQ1ZiyX9Tio51M51pFKZQHN81mzB/kKkGtWtBL4o+sYt2ZD1f/1mS0ihA9fA0zTUPJoNofFkihTD/OObknYVDQ8cCRgewbxu6FWcs+3WtNp4aNFvctqtgtH0M2+Vfn6N4b+Bl4mUSaqaUjBxUHzf8ScQiChbb4VwTur2XVtWZA9p1BXPKu9r3BKyScR85OjUeaTl3TGiWcRks+SYXOz9RPXyUwnVkuGxXoA0FMLk3hFOSdSNr2KLgVGWtXzWZh1u32eiAuI2Gmdkaz6MR/SiLIWlWIEouqFwx81iWByy/R7lGEzU3BCGFlt4taWr/Kntp9+aFovxfvqfoBGbqMXRxS4OcaSJwGE+0ZtQJKmM8tNJe/cewihnbtRUpgwsKf6ALibB2pqCtEFepSUmxnH+93ZJmUlodzdetCyS26Da+xtyt3YjxrOOrh0uwG2OsZk14ImOUkUtVFYjpiRKCag3L2rooti3s3sAytXXStNO/MOq5+v5hVU2GHjRyaLtSQ+W4AtXUzG4BHl4wg4ccMnGIvDttUL7I2PNiPM59h+1mT+Mle/ZSNVz75/j6CyNElZ99+2eqcC1YLcO+tsKI/MeqhMmBskNgOMeZDNgfw=

stages:
- build
- before_deploy
- deploy
jobs:
  include:
  - stage: build
    language: android
    dist: trusty
    jdk:
    - openjdk8
    android:
      components:
      - build-tools-29.0.2
      - platform-tools
      - android-29
    before_install:
    - nvm install 12
    - openssl aes-256-cbc -k "$KEYSTORE_ENC_PASSWORD" -in ./.travis/googleplay.keystore.enc -out ./.travis/googleplay.keystore -d
    install:
    - npm install -g @quasar/cli
    - npm install -g cordova
    script:
    - mvn versions:set -DnewVersion=$TRAVIS_BRANCH
    - mvn versions:commit
    - mvn clean
    - mvn install -P prod
    - mkdir push
    - cp ./backend/target/*.jar ./push
    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ./.travis/googleplay.keystore
      -storepass $GOOGLEPLAY_KEYSTORE_PASSPHRASE ./frontend/src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      googleplay-key
    - "${ANDROID_HOME}/build-tools/29.0.2/zipalign -v 4 ./frontend/src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      ./push/android-app.apk"
    deploy:
    - provider: releases
      api_key: "$GITHUB_TOKEN"
      file:
      - "./push/*"
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
      overwrite: true
    workspaces:
      create:
        name: target
        paths:
        - "./backend/target/"
        - "./push/"
  - stage: before_deploy
    language: sh
    services:
    - docker
    before_deploy:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG -f ./docker/Dockerfile
      ./
    - docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG alex9849/pi-cocktailmaker:latest
    - docker build -t alex9849/pi-cocktailmaker:$TRAVIS_TAG-pi -f ./docker/DockerfilePi
      ./
    - docker tag alex9849/pi-cocktailmaker:$TRAVIS_TAG-pi alex9849/pi-cocktailmaker:latest-pi
    workspaces:
      use: target
    deploy:
      provider: script
      script: bash ./.travis/docker_deploy.sh
      on:
        tags: true
        overwrite: true
