version: '3.7'

services:
  app:
    container_name: Cocktailmaker
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - 8080:8080
  db:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'Chang3M3OnPr0duct1on'
      POSTGRES_DB: 'cocktailmaker'
    volumes:
      - type: volume
        source: cocktail-db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
volumes:
  cocktail-db-data:
