version: '3.7'

services:
  app:
    container_name: Cocktailmaker
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - 8080:8080
  db:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'Chang3M3OnPr0duct1on'
      POSTGRES_DB: 'cocktailmaker'