version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'Chang3M3OnPr0duct1on'
      POSTGRES_DB: 'cocktailmaker'
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: volume
        source: cocktail-db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

volumes:
  cocktail-db-data:
